"""Request and response schemas for the Book resource."""

from pydantic import BaseModel, ConfigDict, Field


class BookBase(BaseModel):
    """Define fields shared by every Book schema."""

    model_config = ConfigDict(
        extra="forbid",
        str_strip_whitespace=True,
        frozen=True,
    )

    title: str = Field(
        min_length=1,
        max_length=200,
        description="The title of the book.",
        examples=["The Pragmatic Programmer"],
    )
    author: str = Field(
        min_length=1,
        max_length=120,
        description="The author of the book.",
        examples=["Andrew Hunt"],
    )
    isbn: str = Field(
        min_length=1,
        description="The book's ISBN. Must be unique.",
        examples=["978-0135957059"],
    )
    published_year: int = Field(
        ge=1450,
        le=2026,
        description="The year the book was published (1450 to the current year).",
        examples=[2019],
    )
    member_id: int = Field(
        gt=0,
        description="The identifier of the member who borrowed this book.",
        examples=[1],
    )


class BookInput(BookBase):
    """Validate client-controlled fields for a Book create or replacement."""


class BookResponse(BookBase):
    """Describe a Book returned by the API."""

    id: int = Field(
        gt=0,
        description="The unique identifier generated by the server.",
        examples=[1],
    )