"""Request and response schemas for the Member resource."""

from pydantic import BaseModel, ConfigDict, EmailStr, Field


class MemberBase(BaseModel):
    """Define fields shared by every Member schema."""

    model_config = ConfigDict(
        extra="forbid",
        str_strip_whitespace=True,
        frozen=True,
    )

    name: str = Field(
        min_length=1,
        max_length=120,
        description="The member's full name.",
        examples=["Ada Lovelace"],
    )
    email: EmailStr = Field(
        description="The member's email address. Must be unique.",
        examples=["ada@example.com"],
    )
    # membership_id is a human-facing label the library assigns (e.g. LIB-000123).
    # It is NOT how the API looks members up: every URL uses the integer id below.
    membership_id: str = Field(
        min_length=1,
        max_length=50,
        description=(
            "A unique library membership label, such as LIB-1. This is stored "
            "data, not the lookup key; URLs address a member by the integer id."
        ),
        examples=["LIB-1"],
    )
    phone: str = Field(
        pattern=r"^\(?\d{3}\)?[-.\s]?\d{3}[-.\s]?\d{4}$",
        description=(
            "US phone number. Accepts an optional parenthesized area code and "
            "hyphen, dot, or space separators, e.g. (555) 123-4567."
        ),
        examples=["555-123-4567"],
    )


class MemberInput(MemberBase):
    """Validate client-controlled fields for a Member create or replacement."""


class MemberResponse(MemberBase):
    """Describe a Member returned by the API."""

    # The server generates the ID, so it appears in responses but not in
    # MemberInput request bodies.
    id: int = Field(
        gt=0,
        description="The unique identifier generated by the server.",
        examples=[1],
    )